/*
Q12: The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

/*
Take 360 as an example. 360 has 24 divisors and its prime factorised form is 
360 = 2^3 * 3^2 * 5

180 = 2^2 * 3^2 * 5

Notice the number of divisors of 360 = (3+1) * (2+1) * (1+1) = 24
This is because we can choose m+1 possible ways per prime where m is the power of the prime.
Eg with 2^3 we can choose either 2, 4, 8 or 1=2^0.

Notice 180 = 360/2 and no of divisors = (2+1) * (2+1) * (1+1) = 18

Now 2 * triangular number = 2 * sum(1, n) = 2 * n * (n + 1) / 2 = n*(n+1)

So twice of the triangular number is a product of 2 consecutive integers aka n * n+1 for nth tranigular number.

Consecutive numbers have distinct prime factors. Thus the number of divisors of the product is just the product of number of divisors of each integer.
The power of prime 2 of the product is just the power of prime 2 of the even integer. As such,
No of divisors of triangular number = (number of divisors) / (power of 2 + 1) * (power of 2)
*/

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>

#define ULL unsigned long long int

int* sieve(int n) {
    bool primes[n + 1];
    int c = n - 1;
    memset(primes, true, sizeof(primes));
    for (int i = 2; i * i <= n; i++) {
        if (primes[i]) {
            for (int j = i * i; j <= n; j += i) {
                if (primes[j]) c--;
                primes[j] = false;
            }
        }
    }

    int* allprimes = (int*)malloc((c + 1) * sizeof(int)); allprimes[c] = -1;

    int index = 0;
    for (int i = 2; i < n; i++) {
        if (primes[i]) {
            allprimes[index] = i; index++;
        }
    }

    return allprimes;
}

int ndiv(int n, int* primes) {
    int p, divisors = 1, currndiv;

    for (int i = 0; primes[i] != -1; i++) {
        currndiv = 1;
        p = primes[i];
        while (n % p == 0) {
            n /= p;
            currndiv++;
        }
        divisors *= currndiv;
    }

    return divisors;
}

int main() {
    clock_t start = clock();
    int* primes = sieve(2000000);

    int triangularnumber;

    for (int i = 1; i < INT_MAX; i++) {
        triangularnumber = i * (i + 1) / 2;
        if (ndiv(triangularnumber, primes) > 500) {
            printf("%d\n", triangularnumber);
            break;
        }
    }

    clock_t end = clock();

    double time = (double)(end - start) / CLOCKS_PER_SEC;

    printf("Time spent: %lf\n", time);

    return 0;
}