/*
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
*/

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>

int floorsqrt(int n) {
    int i;
    for (i = 0; i * i <= n; i++);
    return i - 1;
}

int isSquare(int n) {
    for (int i = 0; i * i <= n; i++) {
        if (i * i == n) return true;
    }
    return false;
}

int isPen(int n) {
    return (isSquare(1 + 24 * n) && ((((1 + floorsqrt(1 + 24 * n)) % 6)) == 0));
}

void genPen(int** arr, int n) {
    *arr = malloc(n * sizeof(int));
    for (int i = 0; i < n; i++) (*arr)[i] = (i + 1) * (3 * i + 2) / 2;
}

int main() {
    printf("STARTING\n"); fflush(stdout);
    int a, b, c, *pen;
    int N = 3000;
    genPen(&pen, N);
    for (int i = 1; i < N; i++) {
        a = pen[i];
        for (int j = i - 1; j >= 0; j--) {
            b = pen[j];
            if (b < 3 * i - 2) break;
            if (isPen(a + b) && isPen(a - b)) {
                printf("%d, %d, %d, %d\n", a, b, a + b, a - b); break;
            }
        }
    }
    return 0;
}